language: python
python:
  - '3.7'
dist: xenial
before_script:
  - pip install codeclimate-test-reporter
  - pip freeze
jobs:
  include:
    - stage: coverage
      script: coverage run setup.py test
      after_success: codeclimate-test-reporter
