language: python
python:
  - '3.7'
dist: xenial
before_script:
  - sudo apt-get install libyaml-dev
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pip install coverage
  - pip freeze
jobs:
  include:
    - stage: coverage
      script: coverage run setup.py test
      after_success: ./cc-test-reporter after-build
